transmission.netcore/Models/AddTorrentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace transmission.netcore.Models
{
    public class AddTorrentViewModel
    {
        [Required]
        [RegularExpression(@"magnet:\?xt=urn:btih:.*")]
        public string Magnet { get; set; }
        [Required]
        public string Path { get; set; }
    }
}

transmission.netcore/Components/TorrentFiles/TorrentFilesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using transmission.netcore.Models;
using Transmission.API.RPC.Entity;

namespace transmission.netcore.Views.TorrentFiles {
    public class TorrentFilesViewComponent : ViewComponent {
        public TorrentFilesViewComponent(ITorrentRepository repository) {
            TorrentRepository = repository;
        }
        protected ITorrentRepository TorrentRepository { get; }

        public async Task<IViewComponentResult> InvokeAsync(int torrentId) {
            TorrentInfo info = TorrentRepository.GetTorrentById(torrentId);
            IEnumerable<FileInfo> files = info.Files.Join(info.FileStats,
                fileInfo => Array.IndexOf(info.Files, fileInfo),
                fileStats => Array.IndexOf(info.FileStats, fileStats),
                (fileInfo, fileStats) => new FileInfo(fileInfo, fileStats));
            ViewData["torrentId"] = torrentId;
            return View("TorrentFiles", files);
        }
    }
}

transmission.netcore/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using transmission.netcore.Models;
using System.Net;
using System.Text;
using Newtonsoft.Json;
using Transmission.API.RPC.Entity;

namespace transmission.netcore.Controllers {
    public class ListController : Controller {
        public ListController(ITorrentRepository repository) {
            TorrentRepository = repository;
        }
        protected ITorrentRepository TorrentRepository { get; }
        private IEnumerable<TorrentViewModel> GetTorrentsByStatus(string status = "") {
            IEnumerable<TorrentViewModel> data;
            switch (status) {
                case "active":
                    data = TorrentRepository.Torrents.Select(t => new TorrentViewModel(t)).Where(t => t.IsActive());
                    break;
                case "inactive":
                    data = TorrentRepository.Torrents.Select(t => new TorrentViewModel(t)).Where(t => !t.IsActive());
                    break;
                case "completed":
                    data = TorrentRepository.Torrents.Select(t => new TorrentViewModel(t)).Where(t => t.IsCompleted());
                    break;
                case "inprocess":
                    data = TorrentRepository.Torrents.Select(t => new TorrentViewModel(t)).Where(t => !t.IsCompleted());
                    break;
                default:
                    data = TorrentRepository.Torrents.Select(t => new TorrentViewModel(t));
                    break;
            }
            return data;
        }

        public IActionResult Index(string status = "") {
            return View(GetTorrentsByStatus(status));
        }
        public IActionResult TorrentList(string status = "") {
            return PartialView(GetTorrentsByStatus(status));
        }
        public IActionResult TorrentFiles(int torrentId) {
            TorrentInfo info = TorrentRepository.GetTorrentById(torrentId);
            IEnumerable<FileInfo> files = info.Files.Join(info.FileStats,
                fileInfo => Array.IndexOf(info.Files, fileInfo),
                fileStats => Array.IndexOf(info.FileStats, fileStats),
                (fileInfo, fileStats) => new FileInfo(fileInfo, fileStats));
            ViewData["torrentId"] = torrentId;
            return PartialView("Components/TorrentFiles/TorrentFiles", files);
        }
        public IActionResult AddTorrent(AddTorrentViewModel torrent, string status = "") {
            if (ModelState.IsValid)
                TorrentRepository.AddTorrent(torrent.Magnet, torrent.Path);
            ViewBag.NewTorrent = torrent;
            return PartialView("TorrentList", GetTorrentsByStatus(status));
        }

        //AJAX API
        public JsonResult GetTorrentsJson(string status = "") {
            return Json(GetTorrentsByStatus(status));
        }
        public JsonResult StartTorrents(int[] ids) {
            TorrentRepository.StartTorrents(ids);
            return Json("OK");
        }
        public JsonResult StopTorrents(int[] ids) {
            TorrentRepository.StopTorrents(ids);
            return Json("OK");
        }
    }
}

transmission.netcore/Views/List/AddTorrentForm.cshtml
@model AddTorrentViewModel
@using (Html.BeginForm()) {
    <div class="row">
        <div class="col-md-6">
            <label class="font-weight-bold">Magnet:</label>
            @(Html.DevExpress().BootstrapTextBoxFor(m => m.Magnet))
        </div>
        <div class="col-md-6">
            <label class="font-weight-bold">Path:</label>
            @(Html.DevExpress().BootstrapTextBoxFor(m => m.Path))
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-right">
            @(Html.DevExpress().BootstrapButton("UpdateButton")
            .Text("Add")
            .ClientSideEvents(clientSideEvents => clientSideEvents.Click("list.onAddTorrentClick"))
            .SettingsBootstrap(settings => settings.RenderOption(BootstrapRenderOption.Link)))
            @(Html.DevExpress().BootstrapButton("CancelButton")
            .Text("Cancel")
            .ClientSideEvents(clientSideEvents => clientSideEvents.Click("list.onCancelAddTorrentClick"))
            .SettingsBootstrap(settings => settings.RenderOption(BootstrapRenderOption.Link)))
        </div>
    </div>
}

transmission.netcore/Views/List/Index.cshtml
@model IEnumerable<TorrentViewModel>
@{
    ViewData["Title"] = "List";
}

<script src="~/js/list.js"></script>
<script src="~/js/charts.js"></script>

@section NavbarMenu {
    @(Html.DevExpress()
                .BootstrapMenu()
                .Name("filterMenu")
                .Items(i => {
                    i.Add()
                       .Text("All").NavigateUrl(Url.Action("Index"));
                    i.Add()
                       .Text("Completed").NavigateUrl(Url.Action("Index", new { status="completed" }));
                    i.Add()
                        .Text("In Process").NavigateUrl(Url.Action("Index", new { status = "inprocess" }));
                    i.Add()
                        .Enabled(false)
                        .Text("|");
                    i.Add()
                        .Text("Active").NavigateUrl(Url.Action("Index", new { status = "active" }));
                    i.Add()
                        .Text("Inactive").NavigateUrl(Url.Action("Index", new { status = "inactive" }));
                })
                .CssClasses(css => css.Control("mr-auto"))
                .SettingsBootstrap(bootstrap => bootstrap.NavbarMode(true)))
    @(Html.DevExpress().BootstrapButtonEdit("searchTextBox")
        .NullText("Search")
        .ClearButton(clearButton => clearButton.DisplayMode(ClearButtonDisplayMode.Always))
        .Buttons(buttons=> buttons.Add().IconCssClass("fas fa-search").Position(ButtonsPosition.Left)))
}

@Html.Hidden("Status", Context.Request.Query["status"])

@Html.Partial("TorrentList", Model)

transmission.netcore/Views/List/LiveCellTemplate.cshtml
@model LiveCellViewModel

<span class="@(Model.FieldName + Model.ID)">@Model.Value</span>

transmission.netcore/Views/List/TorrentDetailInfo.cshtml
@model TorrentViewModel

<div class="form-row">
    <div class="form-group col-12 col-xl-6">
        <label class="font-weight-bold col-6 col-sm-6 col-md-3">Downloaded:</label>
        <div class="col-9 col-sm-6 d-inline">
            @Html.Partial("LiveCellTemplate", new LiveCellViewModel(Model.ID, "Downloaded", Model.Downloaded.String))
        </div>
    </div>
    <div class="form-group col-12 col-xl-6">
        <label class="font-weight-bold col-6 col-sm-6 col-md-3">Uploaded:</label>
        <div class="col-9 col-sm-6 d-inline">
            @Html.Partial("LiveCellTemplate", new LiveCellViewModel(Model.ID, "Uploaded", Model.Uploaded.String))
        </div>
    </div>
</div>
<div class="form-row">
    <div class="form-group col-12 col-xl-6">
        <label class="font-weight-bold col-6 col-sm-6 col-md-3">Location:</label>
        <div class="col-9 col-sm-6 d-inline">
           @Model.DownloadDir
        </div>
    </div>
    <div class="form-group col-12 col-xl-6">
        <label class="font-weight-bold col-6 col-sm-6 col-md-3">Hash:</label>
        <div class="col-9 col-sm-6 d-inline">
            @Model.Hash
        </div>
    </div>
</div>

transmission.netcore/Views/List/TorrentDetailTabs.cshtml
@model TorrentViewModel

@(Html.DevExpress().BootstrapPageControl("DetailsPageControl").TabPages(tabPages => {
    tabPages.Add().Text("Stats").Content(@<text> @Html.Partial("TorrentStats", Model) </text>);
    tabPages.Add().Text("Info").Content(@<text> @Html.Partial("TorrentDetailInfo", Model) </text>);
    tabPages.Add().Text("Files").Content(@<text> @(await Component.InvokeAsync("TorrentFiles", new { torrentId = Model.ID })) </text>);
}))

transmission.netcore/Views/List/TorrentList.cshtml
@model IEnumerable<TorrentViewModel>
@(Html.DevExpress().BootstrapGridView<TorrentViewModel>("TorrentList")
    .KeyFieldName(m => m.ID)
    .Columns(columns => {
        columns.AddCommandColumn().ShowClearFilterButton(true).ShowSelectCheckbox(true).ShowNewButtonInHeader(true);
        columns.Add(m => m.Name);
        columns.Add(m => m.PercentDone).DataItemTemplate(t => @<text>
            @(Html.DevExpress().BootstrapProgressBar("PercentDone" + t.KeyValue)
                                    .Minimum(0).Maximum(100)
                                    .SettingsBootstrap(settings => settings.Animated(true).Striped(true))
                                    .CssClasses(css => css.Control("")) // TODO conditional color
                                    .Value(t.Eval<double>(m => m.PercentDone)))
            </text>);
        columns.Add(m => m.TotalSize);
        columns.Add(m => m.RateDownload)
            .Settings(settings => settings.AllowSort(false))
            .DataItemTemplate(t => @<text> @Html.Partial("LiveCellTemplate", new LiveCellViewModel(t)) </text>);
        columns.Add(m => m.RateUpload)
            .Settings(settings => settings.AllowSort(false))
            .DataItemTemplate(t => @<text> @Html.Partial("LiveCellTemplate", new LiveCellViewModel(t)) </text>);
        columns.Add(m => m.ETA)
            .Settings(settings => settings.AllowSort(false))
            .DataItemTemplate(t => @<text> @Html.Partial("LiveCellTemplate", new LiveCellViewModel(t)) </text>);
    })
    .Templates(templates => templates
        .DetailRow(t => @<text> @Html.Partial("TorrentDetailTabs", Model.First(i => i.ID == (int)t.KeyValue)) </text>)
        .EditForm(t => @<text> @Html.Partial("AddTorrentForm", ViewBag.NewTorrent != null? (AddTorrentViewModel)ViewBag.NewTorrent : new AddTorrentViewModel()) </text>))
    .SettingsDetail(settingsDetail => settingsDetail.ShowDetailRow(true).AllowOnlyOneMasterRowExpanded(true))
    .SettingsPager(settingsPager => settingsPager.Mode(GridViewPagerMode.ShowPager))
    .SettingsSearchPanel(searchPanel => searchPanel.Visible(false).ColumnNames("Name").CustomEditorID("searchTextBox"))
    .SettingsAdaptivity(adaptivity => adaptivity
        .AdaptivityMode(GridViewAdaptivityMode.HideDataCellsWindowLimit)
        .HideDataCellsAtWindowInnerWidth(800)
        .AdaptiveDetailColumnCount(3)
        .AdaptiveDetailLayoutProperties(layout => {
            layout.Items(items => {
                items.Add(m => m.Name).ColSpanSm(8).ShowCaption(false);
                items.Add(m => m.RateDownload).ColSpanSm(2).ShowCaption(false);
                items.Add(m => m.RateUpload).ColSpanSm(2).ShowCaption(false);
                items.Add(m => m.PercentDone).ColSpanSm(12).ShowCaption(false);
            });
        }))
    .Toolbars(toolbars => toolbars.Add().Items(items => {
        items.Add().Name("Start").IconCssClass("fas fa-play");
        items.Add().Name("Stop").IconCssClass("").IconCssClass("fas fa-pause");
    }))
    .ClientSideEvents(clientSideEvents => clientSideEvents
        .Init("list.onGridInit")
        .BeginCallback("list.onGridBeginCallback")
        .ToolbarItemClick("list.onToolbarItemClick"))
    .Routes(routes => routes
        .MapRoute(route => route.RouteType(GridViewRouteType.Default).RouteValues(new { Action = "TorrentList", Controller = "List" }))
        .MapRoute(route => route.RouteType(GridViewRouteType.AddRow).RouteValues(new { Action = "AddTorrent", Controller = "List" })))
    .EnableRowsCache(false)
    .Bind(Model))

transmission.netcore/Views/List/TorrentStats.cshtml
@model TorrentViewModel

@(Html.DevExpress().BootstrapChart("SpeedStats" + Model.ID)
    .SeriesCollection(series => {
        series.AddLineSeries().Name("Download Rate").ArgumentField("Time").ValueField("DownloadSpeed").Axis("Speed").Point(point => point.Visible(false));
        series.AddLineSeries().Name("Upload Rate").ArgumentField("Time").ValueField("UploadSpeed").Axis("Speed").Point(point => point.Visible(false));
    })
    .ArgumentAxis(axis => axis.ArgumentType(typeof(DateTime)))
    .ValueAxisCollection(valueAxisCollection => valueAxisCollection.Add().Name("Speed").ValueType(typeof(int)))
    .SettingsAnimation(animation => animation.Enabled(false))
    .Height(200)
    .ClientSideEvents(clientSideEvents => clientSideEvents.Init("charts.onInit"))
)